### PR TITLE
Add elasticsearch_keystore module

### PR DESCRIPTION
**Pull request by bndabbs**
##### SUMMARY
Adds a new module for managing the Elasticsearch keystore.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
elasticsearch_keystore

### CODE REVIEW

**Comment by rhysmeister** [comment]
Hello @bndabbs,

Does this require a local installation of elastic? The other modules run their tests against a docker-compose launched elastic instance/cluster, all interacting with APIs, so there's nothing currently supporting this type of module. I would suggest creating another role, i.e. setup_local_elastic that could be set into the dependencies of module like this. I've probably got some scope to do this if you don't have the time.

Cheers,

Rhys

**Comment by bndabbs** [comment]
@rhysmeister I started to put together a local role on my fork in the tests branch if you want to use that for reference. I was having trouble getting the test to pass on 2.10.

**Comment by rhysmeister** [comment]
@bndabbs Tests now run. I removed python2.7 for now. Problems were mostly related to the way I implemented the tests for the API based modules. I should probably change this so they all run in docker like this module does. That's something for another day.

There's a couple of small 'sanity' issues remaining...

DOCUMENTATION string....

```
ERROR! module community.elastic.elasticsearch_keystore missing documentation (or could not parse documentation): while scanning a simple key
  in "<unicode string>", line 12, column 1
could not find expected ':'
  in "<unicode string>", line 13, column 1
```

PEP8...

`ERROR: plugins/modules/elasticsearch_keystore.py:143:17: E122: continuation line missing indentation or outdented`

pylint...

```
ERROR: plugins/modules/elasticsearch_keystore.py:184:20: blacklisted-name: Black listed name "_"
ERROR: plugins/modules/elasticsearch_keystore.py:193:16: blacklisted-name: Black listed name "_"
ERROR: plugins/modules/elasticsearch_keystore.py:204:16: blacklisted-name: Black listed name "_"
```

A couple of points...

- Any reason we can't call this elastic_keyspace in the keeping with the other modules?
- Can we add tests for check_mode?

**Comment by bndabbs** [comment]
The sanity issues have been addressed on my testing branch. 

Regarding the name, my original thought was to have a module for each product's keystore. Now that I think about it, though, it probably makes more sense to have the product as a parameter. I'm going to look into how involved that will be to add the other products to this one.

Good call on check_mode. I'll add that to the tests.

**Comment by rhysmeister** [comment]
Hi @bndabbs If there's no objections I'll correct the sanity issues and commit this. I plan to do a Galaxy release and it would be good to include this.

Rhys

**Comment by bndabbs** [comment]
> Hi @bndabbs If there's no objections I'll correct the sanity issues and commit this. I plan to do a Galaxy release and it would be good to include this.
> 
> Rhys

That sounds great. Sorry about the delay; the last month has been really busy.

**Comment by rhysmeister** [comment]
> > Hi @bndabbs If there's no objections I'll correct the sanity issues and commit this. I plan to do a Galaxy release and it would be good to include this.
> > Rhys
> 
> That sounds great. Sorry about the delay; the last month has been really busy.

No probs. There aren't any deadlines here!

**Pull request merged**
